In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client.PGAStats

wells_fargo= db.wellsFargo
raw_data = pd.DataFrame(list(wells_fargo.find()))

In [2]:
raw_data

,_id,earnings,fedExPoints,name,r1,r2,r3,r4,rank,score,total,year
0,5cbe01628cc3ae72ca486ac9,"$1,386,000.00",500,Jason Day,69,67,67,69,1,-12,272,2018
1,5cbe01628cc3ae72ca486aca,"$677,600.00",245,Aaron Wise,68,68,70,68,T2,-10,274,2018
2,5cbe01628cc3ae72ca486acb,"$677,600.00",245,Nick Watney,72,67,66,69,T2,-10,274,2018
3,5cbe01638cc3ae72ca486acc,"$369,600.00",135,Bryson DeChambeau,75,65,66,70,4,-8,276,2018
4,5cbe01638cc3ae72ca486acd,"$281,050.00",100,Phil Mickelson,72,72,64,69,T5,-7,277,2018
5,5cbe01638cc3ae72ca486ace,"$281,050.00",100,Paul Casey,69,68,69,71,T5,-7,277,2018
6,5cbe01638cc3ae72ca486acf,"$281,050.00",100,Peter Uihlein,72,72,62,71,T5,-7,277,2018
7,5cbe01638cc3ae72ca486ad0,"$238,700.00",85,Patrick Reed,71,71,67,69,8,-6,278,2018
8,5cbe01638cc3ae72ca486ad1,"$200,200.00",73,Emiliano Grillo,68,71,71,69,T9,-5,279,2018
9,5cbe01638cc3ae72ca486ad2,"$200,200.00",73,Luke List,70,72,67,70,T9,-5,279,2018
10,5cbe01638cc3ae72ca486ad3,"$200,200.00",73,Charl Schwartzel,70,67,70,72,T9,-5,279,2018
11,5cbe01638cc3ae72ca486ad4,"$200,200.00",73,Sam Saunders,70,69,68,72,T9,-5,279,2018
12,5cbe01638cc3ae72ca486ad5,"$148,867.00",57,Kyle Stanley,67,72,71,70,T13,-4,280,2018
13,5cbe01638cc3ae72ca486ad6,"$148,867.00",57,Talor Gooch,71,72,66,71,T13,-4,280,2018
14,5cbe01638cc3ae72ca486ad7,"$148,867.00",57,Johnson Wagner,67,71,69,73,T13,-4,280,2018
15,5cbe01638cc3ae72ca486ad8,"$115,500.00",49,Joel Dahmen,70,71,70,70,T16,-3,281,2018
16,5cbe01638cc3ae72ca486ad9,"$115,500.00",49,Francesco Molinari,70,72,68,71,T16,-3,281,2018
17,5cbe01638cc3ae72ca486ada,"$115,500.00",49,Chesson Hadley,70,74,66,71,T16,-3,281,2018
18,5cbe01638cc3ae72ca486adb,"$115,500.00",49,Rory McIlroy,68,76,66,71,T16,-3,281,2018
19,5cbe01638cc3ae72ca486adc,"$115,500.00",49,Adam Hadwin,73,71,65,72,T16,-3,281,2018
20,5cbe01638cc3ae72ca486add,"$77,000.00",38,Tony Finau,69,76,71,66,T21,-2,282,2018
21,5cbe01638cc3ae72ca486ade,"$77,000.00",38,Webb Simpson,72,70,71,69,T21,-2,282,2018
22,5cbe01638cc3ae72ca486adf,"$77,000.00",38,Justin Thomas,73,69,70,70,T21,-2,282,2018
23,5cbe01638cc3ae72ca486ae0,"$77,000.00",38,Greg Chalmers,71,70,70,71,T21,-2,282,2018
24,5cbe01638cc3ae72ca486ae1,"$77,000.00",38,Charles Howell III,71,68,71,72,T21,-2,282,2018
25,5cbe01638cc3ae72ca486ae2,"$77,000.00",38,Rickie Fowler,72,69,68,73,T21,-2,282,2018
26,5cbe01638cc3ae72ca486ae3,"$52,360.00",28,Rory Sabbatini,71,71,73,68,T27,-1,283,2018
27,5cbe01638cc3ae72ca486ae4,"$52,360.00",28,Seamus Power,74,71,68,70,T27,-1,283,2018
28,5cbe01638cc3ae72ca486ae5,"$52,360.00",28,Alex Cejka,70,71,71,71,T27,-1,283,2018
29,5cbe01638cc3ae72ca486ae6,"$52,360.00",28,Ted Potter Jr.,72,71,69,71,T27,-1,283,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
1218,5cbe018b8cc3ae72ca486f8b,--,0,Mark Wilson,74,76,--,--,-,CUT,150,2011
1219,5cbe018b8cc3ae72ca486f8c,--,0,Nick O'Hern,77,77,--,--,-,CUT,154,2012
1220,5cbe018b8cc3ae72ca486f8d,--,0,Jim Renner,80,70,--,--,-,CUT,150,2011
1221,5cbe018b8cc3ae72ca486f8e,--,0,Bryan Bigley,80,75,--,--,-,CUT,155,2012
1222,5cbe018b8cc3ae72ca486f8f,--,0,Chris Kirk,78,72,--,--,-,CUT,150,2011
1223,5cbe018b8cc3ae72ca486f90,--,0,D.J. Trahan,--,--,--,--,-,WD,--,2012
1224,5cbe018b8cc3ae72ca486f91,--,0,Jeff Maggert,75,76,--,--,-,CUT,151,2011
1225,5cbe018b8cc3ae72ca486f92,--,0,Anthony Kim,74,--,--,--,-,WD,74,2012
1226,5cbe018c8cc3ae72ca486f93,--,0,Derek Lamely,76,75,--,--,-,CUT,151,2011
1227,5cbe018c8cc3ae72ca486f94,--,0,Bo Van Pelt,78,--,--,--,-,WD,78,2012
1228,5cbe018c8cc3ae72ca486f95,--,0,Kyle Thompson,77,74,--,--,-,CUT,151,2011
1229,5cbe018c8cc3ae72ca486f96,--,0,Charlie Beljan,78,--,--,--,-,WD,78,2012
1230,5cbe018c8cc3ae72ca486f97,--,0,Brad Faxon,77,74,--,--,-,CUT,151,2011
1231,5cbe018c8cc3ae72ca486f98,--,0,Dean Wilson,74,77,--,--,-,CUT,151,2011
1232,5cbe018c8cc3ae72ca486f99,--,0,Nick Watney,76,75,--,--,-,CUT,151,2011
1233,5cbe018c8cc3ae72ca486f9a,--,0,Dustin Johnson,72,79,--,--,-,CUT,151,2011
1234,5cbe018c8cc3ae72ca486f9b,--,0,Henrik Stenson,75,76,--,--,-,CUT,151,2011
1235,5cbe018c8cc3ae72ca486f9c,--,0,D.J. Brigman,73,78,--,--,-,CUT,151,2011
1236,5cbe018c8cc3ae72ca486f9d,--,0,Justin Hicks,74,78,--,--,-,CUT,152,2011
1237,5cbe018c8cc3ae72ca486f9e,--,0,Garrett Willis,78,75,--,--,-,CUT,153,2011
1238,5cbe018c8cc3ae72ca486f9f,--,0,Colt Knost,77,76,--,--,-,CUT,153,2011
1239,5cbe018c8cc3ae72ca486fa0,--,0,Shaun Micheel,75,78,--,--,-,CUT,153,2011
1240,5cbe018c8cc3ae72ca486fa1,--,0,Kevin Kisner,79,74,--,--,-,CUT,153,2011
1241,5cbe018c8cc3ae72ca486fa2,--,0,Bryan Bigley,78,76,--,--,-,CUT,154,2011
1242,5cbe018c8cc3ae72ca486fa3,--,0,David Hearn,79,76,--,--,-,CUT,155,2011
1243,5cbe018c8cc3ae72ca486fa4,--,0,Jeff Klauk,80,75,--,--,-,CUT,155,2011
1244,5cbe018c8cc3ae72ca486fa5,--,0,Kevin Stadler,80,76,--,--,-,CUT,156,2011
1245,5cbe018c8cc3ae72ca486fa6,--,0,Daniel Summerhays,78,78,--,--,-,CUT,156,2011
1246,5cbe018c8cc3ae72ca486fa7,--,0,Todd Camplin,83,75,--,--,-,CUT,158,2011
1247,5cbe018c8cc3ae72ca486fa8,--,0,Matt Bettencourt,79,--,--,--,-,WD,79,2011

In [6]:
raw_data2017 = raw_data[raw_data.year!='2018'].copy()

In [16]:
clean_data1 = raw_data2017[['r1','r2','total','name','year']].copy()

In [17]:
clean_data1 = clean_data1[raw_data.r1!='--'].copy()
clean_data1 = clean_data1[raw_data.r2!='--'].copy()
clean_data1 = clean_data1[raw_data.total!='--'].copy()

/Users/davidbarlow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.
/Users/davidbarlow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

/Users/davidbarlow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

In [24]:
clean_data1[['r1','r2','total','year']]=clean_data1[['r1','r2','total','year']].astype(float)

In [25]:
clean_data1.reset_index(drop=True)
clean_data1

        r1    r2  total                  name    year
156   71.0  69.0  278.0          Brian Harman  2017.0
157   70.0  75.0  279.0        Dustin Johnson  2017.0
158   72.0  69.0  279.0             Pat Perez  2017.0
159   69.0  71.0  280.0              Jon Rahm  2017.0
160   70.0  71.0  281.0        Smylie Kaufman  2017.0
161   72.0  70.0  281.0            Kevin Tway  2017.0
162   69.0  74.0  281.0         Seung-yul Noh  2017.0
163   69.0  73.0  282.0     Jonathan Randolph  2017.0
164   70.0  69.0  282.0      Billy Hurley III  2017.0
165   71.0  69.0  282.0           Nick Taylor  2017.0
166   72.0  70.0  282.0         Byeong-Hun An  2017.0
167   70.0  75.0  283.0            Paul Casey  2017.0
168   73.0  69.0  283.0           D.A. Points  2017.0
169   70.0  71.0  283.0       Morgan Hoffmann  2017.0
170   72.0  70.0  283.0             Zac Blair  2017.0
171   71.0  69.0  283.0         Vaughn Taylor  2017.0
172   70.0  71.0  283.0          Patrick Reed  2017.0
173   73.0  71.0  284.0          Brandon Hagy  2017.0
174   68.0  72.0  284.0            Ben Martin  2017.0
175   71.0  73.0  284.0          Zach Johnson  2017.0
176   72.0  70.0  284.0       David Lingmerth  2017.0
177   71.0  71.0  284.0       Graeme McDowell  2017.0
178   71.0  72.0  284.0        Phil Mickelson  2017.0
179   71.0  70.0  285.0     Xander Schauffele  2017.0
180   72.0  71.0  285.0          Robert Streb  2017.0
181   71.0  73.0  285.0           J.T. Poston  2017.0
182   69.0  71.0  285.0  Rafael Cabrera Bello  2017.0
183   75.0  70.0  285.0           Shane Lowry  2017.0
184   70.0  72.0  285.0      Mark D. Anderson  2017.0
185   66.0  72.0  285.0    Francesco Molinari  2017.0
...    ...   ...    ...                   ...     ...
1213  77.0  75.0  152.0      Billy Hurley III  2012.0
1214  75.0  74.0  149.0         Lanto Griffin  2011.0
1215  73.0  80.0  153.0         Nick Flanagan  2012.0
1216  80.0  70.0  150.0         Chris DiMarco  2011.0
1217  76.0  77.0  153.0         Rick Lewallen  2012.0
1218  74.0  76.0  150.0           Mark Wilson  2011.0
1219  77.0  77.0  154.0           Nick O'Hern  2012.0
1220  80.0  70.0  150.0            Jim Renner  2011.0
1221  80.0  75.0  155.0          Bryan Bigley  2012.0
1222  78.0  72.0  150.0            Chris Kirk  2011.0
1224  75.0  76.0  151.0          Jeff Maggert  2011.0
1226  76.0  75.0  151.0          Derek Lamely  2011.0
1228  77.0  74.0  151.0         Kyle Thompson  2011.0
1230  77.0  74.0  151.0            Brad Faxon  2011.0
1231  74.0  77.0  151.0           Dean Wilson  2011.0
1232  76.0  75.0  151.0           Nick Watney  2011.0
1233  72.0  79.0  151.0        Dustin Johnson  2011.0
1234  75.0  76.0  151.0        Henrik Stenson  2011.0
1235  73.0  78.0  151.0          D.J. Brigman  2011.0
1236  74.0  78.0  152.0          Justin Hicks  2011.0
1237  78.0  75.0  153.0        Garrett Willis  2011.0
1238  77.0  76.0  153.0            Colt Knost  2011.0
1239  75.0  78.0  153.0         Shaun Micheel  2011.0
1240  79.0  74.0  153.0          Kevin Kisner  2011.0
1241  78.0  76.0  154.0          Bryan Bigley  2011.0
1242  79.0  76.0  155.0           David Hearn  2011.0
1243  80.0  75.0  155.0            Jeff Klauk  2011.0
1244  80.0  76.0  156.0         Kevin Stadler  2011.0
1245  78.0  78.0  156.0     Daniel Summerhays  2011.0
1246  83.0  75.0  158.0          Todd Camplin  2011.0

[1079 rows x 5 columns]

In [26]:
this_year = clean_data1.copy()

In [27]:
prev_year = clean_data1.copy()
prev_year['year']=prev_year['year']+1
prev_year['avg_round']=prev_year['total']/4

In [28]:
data1 = pd.merge(prev_year,this_year, on=['name','year'], how='inner')

In [29]:
data1

,r1_x,r2_x,total_x,name,year,avg_round,r1_y,r2_y,total_y
0,70.0,71.0,279.0,James Hahn,2017.0,69.75,72.0,71.0,291.0
1,71.0,66.0,279.0,Roberto Castro,2017.0,69.75,72.0,74.0,146.0
2,69.0,70.0,281.0,Phil Mickelson,2017.0,70.25,71.0,72.0,284.0
3,71.0,70.0,282.0,Lucas Glover,2017.0,70.50,71.0,73.0,290.0
4,75.0,69.0,283.0,Fabian Gomez,2017.0,70.75,71.0,73.0,221.0
5,71.0,67.0,284.0,Chesson Hadley,2017.0,71.00,77.0,76.0,153.0
6,68.0,73.0,284.0,Tim Wilkinson,2017.0,71.00,75.0,74.0,149.0
7,69.0,72.0,285.0,Retief Goosen,2017.0,71.25,70.0,72.0,289.0
8,71.0,71.0,286.0,David Lingmerth,2017.0,71.50,72.0,70.0,284.0
9,70.0,74.0,286.0,William McGirt,2017.0,71.50,75.0,74.0,149.0
10,71.0,71.0,286.0,Harris English,2017.0,71.50,75.0,77.0,152.0
11,72.0,70.0,286.0,Francesco Molinari,2017.0,71.50,66.0,72.0,285.0
12,73.0,70.0,286.0,Adam Scott,2017.0,71.50,71.0,74.0,287.0
13,68.0,71.0,286.0,Daniel Berger,2017.0,71.50,71.0,72.0,287.0
14,72.0,69.0,287.0,Harold Varner III,2017.0,71.75,74.0,74.0,148.0
15,72.0,69.0,287.0,Patton Kizzire,2017.0,71.75,73.0,71.0,293.0
16,75.0,70.0,288.0,Robert Streb,2017.0,72.00,72.0,71.0,285.0
17,73.0,71.0,288.0,Patrick Reed,2017.0,72.00,70.0,71.0,283.0
18,72.0,72.0,288.0,Johnson Wagner,2017.0,72.00,72.0,74.0,146.0
19,74.0,71.0,288.0,Camilo Villegas,2017.0,72.00,74.0,75.0,149.0
20,72.0,73.0,289.0,Vaughn Taylor,2017.0,72.25,71.0,69.0,283.0
21,69.0,70.0,289.0,Brian Harman,2017.0,72.25,71.0,69.0,278.0
22,70.0,72.0,289.0,Chris Stroud,2017.0,72.25,74.0,72.0,146.0
23,69.0,73.0,289.0,Boo Weekley,2017.0,72.25,72.0,75.0,147.0
24,70.0,68.0,289.0,Mark Hubbard,2017.0,72.25,72.0,75.0,147.0
25,71.0,73.0,290.0,Derek Ernst,2017.0,72.50,73.0,79.0,152.0
26,72.0,72.0,290.0,Kyle Reifers,2017.0,72.50,72.0,70.0,288.0
27,65.0,74.0,290.0,Steve Wheatcroft,2017.0,72.50,74.0,75.0,149.0
28,72.0,70.0,290.0,Cameron Tringale,2017.0,72.50,74.0,72.0,146.0
29,73.0,72.0,290.0,Tom Hoge,2017.0,72.50,71.0,75.0,146.0
...,...,...,...,...,...,...,...,...,...
500,74.0,72.0,146.0,Rocco Mediate,2012.0,36.50,68.0,69.0,284.0
501,70.0,79.0,149.0,Jeff Maggert,2013.0,37.25,73.0,76.0,149.0
502,75.0,72.0,147.0,Rory McIlroy,2012.0,36.75,70.0,68.0,274.0
503,75.0,72.0,147.0,Jhonattan Vegas,2012.0,36.75,72.0,72.0,144.0
504,72.0,75.0,147.0,Troy Matteson,2012.0,36.75,74.0,69.0,285.0
505,76.0,71.0,147.0,Kris Blanks,2012.0,36.75,75.0,73.0,148.0
506,74.0,73.0,147.0,Tommy Gainey,2012.0,36.75,68.0,72.0,284.0
507,77.0,71.0,148.0,Blake Adams,2012.0,37.00,74.0,73.0,147.0
508,75.0,75.0,150.0,Erik Compton,2013.0,37.50,76.0,76.0,152.0
509,75.0,73.0,148.0,David Duval,2012.0,37.00,76.0,74.0,150.0
510,71.0,79.0,150.0,Charles Howell III,2013.0,37.50,72.0,72.0,284.0
511,74.0,76.0,150.0,Jason Kokrak,2013.0,37.50,68.0,70.0,291.0
512,77.0,74.0,151.0,Scott Stallings,2013.0,37.75,77.0,73.0,150.0
513,73.0,78.0,151.0,Bobby Gates,2013.0,37.75,71.0,76.0,147.0
514,71.0,78.0,149.0,D.A. Points,2012.0,37.25,66.0,68.0,274.0
515,75.0,74.0,149.0,Camilo Villegas,2012.0,37.25,71.0,70.0,283.0
516,80.0,70.0,150.0,Chris DiMarco,2012.0,37.50,69.0,75.0,144.0
517,74.0,76.0,150.0,Mark Wilson,2012.0,37.50,77.0,73.0,150.0
518,78.0,72.0,150.0,Chris Kirk,2012.0,37.50,75.0,67.0,288.0
519,75.0,76.0,151.0,Jeff Maggert,2012.0,37.75,70.0,79.0,149.0
520,76.0,75.0,151.0,Derek Lamely,2012.0,37.75,76.0,73.0,149.0
521,77.0,74.0,151.0,Kyle Thompson,2012.0,37.75,71.0,74.0,145.0
522,76.0,75.0,151.0,Nick Watney,2012.0,37.75,68.0,64.0,278.0
523,75.0,76.0,151.0,Henrik Stenson,2012.0,37.75,74.0,70.0,144.0
524,77.0,76.0,153.0,Colt Knost,2012.0,38.25,73.0,72.0,145.0
525,79.0,74.0,153.0,Kevin Kisner,2012.0,38.25,72.0,72.0,144.0
526,78.0,76.0,154.0,Bryan Bigley,2012.0,38.50,80.0,75.0,155.0
527,79.0,76.0,155.0,David Hearn,2012.0,38.75,70.0,72.0,289.0
528,80.0,76.0,156.0,Kevin Stadler,2012.0,39.00,68.0,74.0,282.0
529,78.0,78.0,156.0,Daniel Summerhays,2012.0,39.00,71.0,77.0,148.0

In [31]:
data1['r2_lt_avg'] = np.where(data1['r2_y']<=data1['avg_round'],1,0) 
data1['r1_lt_avg'] = np.where(data1['r1_y']<=data1['avg_round'],1,0)

In [33]:
data = data1[['r2_lt_avg','r1_lt_avg','avg_round']]

In [44]:
data

     r2_lt_avg  r1_lt_avg  avg_round
0            0          0      69.75
1            0          0      69.75
2            0          0      70.25
3            0          0      70.50
4            0          0      70.75
5            0          0      71.00
6            0          0      71.00
7            0          1      71.25
8            1          0      71.50
9            0          0      71.50
10           0          0      71.50
11           0          1      71.50
12           0          1      71.50
13           0          1      71.50
14           0          0      71.75
15           1          0      71.75
16           1          1      72.00
17           1          1      72.00
18           0          1      72.00
19           0          0      72.00
20           1          1      72.25
21           1          1      72.25
22           1          0      72.25
23           0          1      72.25
24           0          1      72.25
25           0          0      72.50
26           1          1      72.50
27           0          0      72.50
28           1          0      72.50
29           0          1      72.50
..         ...        ...        ...
500          0          0      36.50
501          0          0      37.25
502          0          0      36.75
503          0          0      36.75
504          0          0      36.75
505          0          0      36.75
506          0          0      36.75
507          0          0      37.00
508          0          0      37.50
509          0          0      37.00
510          0          0      37.50
511          0          0      37.50
512          0          0      37.75
513          0          0      37.75
514          0          0      37.25
515          0          0      37.25
516          0          0      37.50
517          0          0      37.50
518          0          0      37.50
519          0          0      37.75
520          0          0      37.75
521          0          0      37.75
522          0          0      37.75
523          0          0      37.75
524          0          0      38.25
525          0          0      38.25
526          0          0      38.50
527          0          0      38.75
528          0          0      39.00
529          0          0      39.00

[530 rows x 3 columns]

In [55]:
y = data['r2_lt_avg']
x1 = data[['r1_lt_avg','avg_round']]

In [56]:
x = sm.add_constant(x1)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()
# Get the regression summary
results_log.summary()

Optimization terminated successfully.
         Current function value: 0.324706
         Iterations 11

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:              r2_lt_avg   No. Observations:                  530
Model:                          Logit   Df Residuals:                      527
Method:                           MLE   Df Model:                            2
Date:                Mon, 22 Apr 2019   Pseudo R-squ.:                  0.3370
Time:                        11:40:33   Log-Likelihood:                -172.09
converged:                       True   LL-Null:                       -259.57
                                        LLR p-value:                 1.020e-38
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -43.5193      8.571     -5.078      0.000     -60.318     -26.721
r1_lt_avg      0.2392      0.266      0.900      0.368      -0.282       0.760
avg_round      0.6006      0.120      4.990      0.000       0.365       0.836
==============================================================================

Possibly complete quasi-separation: A fraction 0.45 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [60]:
def confusion_matrix(data,actual_values,model):
        
        # Confusion matrix 
        
        # Parameters
        # ----------
        # data: data frame or array
            # data is a data frame formatted in the same way as your input data (without the actual values)
            # e.g. const, var1, var2, etc. Order is very important!
        # actual_values: data frame or array
            # These are the actual values from the test_data
            # In the case of a logistic regression, it should be a single column with 0s and 1s
            
        # model: a LogitResults object
            # this is the variable where you have the fitted model 
            # e.g. results_log in this course
        # ----------
        
        #Predict the values using the Logit model
        pred_values = model.predict(data)
        # Specify the bins 
        bins=np.array([0,0.5,1])
        # Create a histogram, where if values are between 0 and 0.5 tell will be considered 0
        # if they are between 0.5 and 1, they will be considered 1
        cm = np.histogram2d(actual_values, pred_values, bins=bins)[0]
        # Calculate the accuracy
        accuracy = (cm[0,0]+cm[1,1])/cm.sum()
        # Return the confusion matrix and 
        return cm, accuracy

In [88]:
confusion_matrix(x,y,results_log)

(array([[402.00, 26.00],
        [70.00, 32.00]]), 0.8188679245283019)

In [57]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
# Should you want to go back to the default formatting, uncomment and execute the line below
#np.set_printoptions(formatter=None)
results_log.predict()

array([0.16, 0.16, 0.21, 0.24, 0.26, 0.29, 0.29, 0.38, 0.36, 0.36, 0.36,
       0.42, 0.42, 0.42, 0.39, 0.39, 0.49, 0.49, 0.49, 0.43, 0.53, 0.53,
       0.47, 0.53, 0.53, 0.51, 0.56, 0.51, 0.51, 0.56, 0.56, 0.54, 0.54,
       0.60, 0.60, 0.64, 0.67, 0.68, 0.76, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.03, 0.00, 0.08, 0.08, 0.11,
       0.00, 0.14, 0.00, 0.11, 0.00, 0.13, 0.13, 0.00, 0.14, 0.14, 0.14,
       0.00, 0.14, 0.16, 0.16, 0.16, 0.00, 0.22, 0.19, 0.22, 0.00, 0.21,
       0.00, 0.24, 0.24, 0.24, 0.00, 0.00, 0.24, 0.00, 0.31, 0.00, 0.26,
       0.26, 0.00, 0.31, 0.00, 0.31, 0.00, 0.26, 0.26, 0.00, 0.26, 0.35,
       0.00, 0.35, 0.00, 0.29, 0.00, 0.35, 0.00, 0.29, 0.29, 0.29, 0.33,
       0.33, 0.33, 0.38, 0.33, 0.42, 0.36, 0.45, 0.39, 0.39, 0.39, 0.43,
       0.47, 0.47, 0.53, 0.64, 0.67, 0.00, 0.08, 0.00, 0.10, 0.14, 0.13,
       0.00, 0.00, 0.16, 0.00, 0.20, 0.00, 0.22, 0.00, 0.19, 0.25, 0.00,
       0.25, 0.00, 0.21, 0.00, 0.28, 0.24, 0.00, 0.28, 0.00, 0.00, 0.00,
       0.26, 0.00, 0.31, 0.26, 0.35, 0.00, 0.35, 0.00, 0.35, 0.00, 0.29,
       0.35, 0.00, 0.38, 0.00, 0.38, 0.00, 0.33, 0.00, 0.38, 0.33, 0.00,
       0.38, 0.00, 0.33, 0.00, 0.36, 0.00, 0.42, 0.42, 0.00, 0.00, 0.42,
       0.00, 0.39, 0.45, 0.39, 0.39, 0.39, 0.00, 0.49, 0.00, 0.49, 0.49,
       0.43, 0.47, 0.00, 0.47, 0.00, 0.51, 0.00, 0.60, 0.00, 0.54, 0.60,
       0.00, 0.58, 0.00, 0.62, 0.00, 0.73, 0.73, 0.00, 0.79, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.19, 0.00, 0.00, 0.25, 0.00, 0.24, 0.24, 0.00, 0.31,
       0.00, 0.26, 0.26, 0.26, 0.29, 0.00, 0.35, 0.00, 0.00, 0.35, 0.35,
       0.00, 0.00, 0.33, 0.00, 0.33, 0.33, 0.00, 0.00, 0.36, 0.42, 0.36,
       0.36, 0.39, 0.39, 0.45, 0.39, 0.49, 0.43, 0.49, 0.49, 0.47, 0.53,
       0.53, 0.53, 0.53, 0.51, 0.51, 0.51, 0.56, 0.51, 0.56, 0.60, 0.54,
       0.54, 0.54, 0.54, 0.58, 0.67, 0.62, 0.70, 0.70, 0.79, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.08, 0.08, 0.11, 0.10, 0.13, 0.00, 0.13, 0.00, 0.16, 0.18,
       0.16, 0.00, 0.16, 0.16, 0.00, 0.16, 0.00, 0.16, 0.00, 0.22, 0.00,
       0.22, 0.19, 0.00, 0.07, 0.22, 0.07, 0.08, 0.21, 0.10, 0.21, 0.11,
       0.00, 0.13, 0.21, 0.13, 0.00, 0.13, 0.24, 0.28, 0.18, 0.00, 0.18,
       0.24, 0.18, 0.14, 0.24, 0.18, 0.00, 0.26, 0.14, 0.00, 0.26, 0.16,
       0.00, 0.20, 0.00, 0.31, 0.20, 0.00, 0.16, 0.26, 0.00, 0.26, 0.22,
       0.29, 0.29, 0.21, 0.29, 0.21, 0.21, 0.29, 0.29, 0.33, 0.42, 0.36,
       0.42, 0.31, 0.26, 0.42, 0.31, 0.39, 0.26, 0.39, 0.31, 0.39, 0.26,
       0.49, 0.43, 0.43, 0.43, 0.35, 0.49, 0.35, 0.47, 0.53, 0.33, 0.56,
       0.33, 0.51, 0.38, 0.38, 0.36, 0.42, 0.42, 0.42, 0.45, 0.00, 0.45,
       0.00, 0.53, 0.00, 0.47, 0.00, 0.53, 0.00, 0.56, 0.56, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
       0.00, 0.00])

In [58]:
np.array(y)
results_log.pred_table()

array([[402.00, 26.00],
       [70.00, 32.00]])

In [59]:
cm_df = pd.DataFrame(results_log.pred_table())
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

          Predicted 0  Predicted 1
Actual 0        402.0         26.0
Actual 1         70.0         32.0

In [63]:
cm = np.array(cm_df)
# Calculate the accuracy of the model
accuracy_train = (cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.8188679245283019

Test the model on 2018 data

In [76]:
raw_data_2017 = raw_data[(raw_data['year']=='2017')].copy()
raw_data_2018 = raw_data[(raw_data['year']=='2018')].copy()
raw_data_2018

,_id,earnings,fedExPoints,name,r1,r2,r3,r4,rank,score,total,year
0,5cbe01628cc3ae72ca486ac9,"$1,386,000.00",500,Jason Day,69,67,67,69,1,-12,272,2018
1,5cbe01628cc3ae72ca486aca,"$677,600.00",245,Aaron Wise,68,68,70,68,T2,-10,274,2018
2,5cbe01628cc3ae72ca486acb,"$677,600.00",245,Nick Watney,72,67,66,69,T2,-10,274,2018
3,5cbe01638cc3ae72ca486acc,"$369,600.00",135,Bryson DeChambeau,75,65,66,70,4,-8,276,2018
4,5cbe01638cc3ae72ca486acd,"$281,050.00",100,Phil Mickelson,72,72,64,69,T5,-7,277,2018
5,5cbe01638cc3ae72ca486ace,"$281,050.00",100,Paul Casey,69,68,69,71,T5,-7,277,2018
6,5cbe01638cc3ae72ca486acf,"$281,050.00",100,Peter Uihlein,72,72,62,71,T5,-7,277,2018
7,5cbe01638cc3ae72ca486ad0,"$238,700.00",85,Patrick Reed,71,71,67,69,8,-6,278,2018
8,5cbe01638cc3ae72ca486ad1,"$200,200.00",73,Emiliano Grillo,68,71,71,69,T9,-5,279,2018
9,5cbe01638cc3ae72ca486ad2,"$200,200.00",73,Luke List,70,72,67,70,T9,-5,279,2018
10,5cbe01638cc3ae72ca486ad3,"$200,200.00",73,Charl Schwartzel,70,67,70,72,T9,-5,279,2018
11,5cbe01638cc3ae72ca486ad4,"$200,200.00",73,Sam Saunders,70,69,68,72,T9,-5,279,2018
12,5cbe01638cc3ae72ca486ad5,"$148,867.00",57,Kyle Stanley,67,72,71,70,T13,-4,280,2018
13,5cbe01638cc3ae72ca486ad6,"$148,867.00",57,Talor Gooch,71,72,66,71,T13,-4,280,2018
14,5cbe01638cc3ae72ca486ad7,"$148,867.00",57,Johnson Wagner,67,71,69,73,T13,-4,280,2018
15,5cbe01638cc3ae72ca486ad8,"$115,500.00",49,Joel Dahmen,70,71,70,70,T16,-3,281,2018
16,5cbe01638cc3ae72ca486ad9,"$115,500.00",49,Francesco Molinari,70,72,68,71,T16,-3,281,2018
17,5cbe01638cc3ae72ca486ada,"$115,500.00",49,Chesson Hadley,70,74,66,71,T16,-3,281,2018
18,5cbe01638cc3ae72ca486adb,"$115,500.00",49,Rory McIlroy,68,76,66,71,T16,-3,281,2018
19,5cbe01638cc3ae72ca486adc,"$115,500.00",49,Adam Hadwin,73,71,65,72,T16,-3,281,2018
20,5cbe01638cc3ae72ca486add,"$77,000.00",38,Tony Finau,69,76,71,66,T21,-2,282,2018
21,5cbe01638cc3ae72ca486ade,"$77,000.00",38,Webb Simpson,72,70,71,69,T21,-2,282,2018
22,5cbe01638cc3ae72ca486adf,"$77,000.00",38,Justin Thomas,73,69,70,70,T21,-2,282,2018
23,5cbe01638cc3ae72ca486ae0,"$77,000.00",38,Greg Chalmers,71,70,70,71,T21,-2,282,2018
24,5cbe01638cc3ae72ca486ae1,"$77,000.00",38,Charles Howell III,71,68,71,72,T21,-2,282,2018
25,5cbe01638cc3ae72ca486ae2,"$77,000.00",38,Rickie Fowler,72,69,68,73,T21,-2,282,2018
26,5cbe01638cc3ae72ca486ae3,"$52,360.00",28,Rory Sabbatini,71,71,73,68,T27,-1,283,2018
27,5cbe01638cc3ae72ca486ae4,"$52,360.00",28,Seamus Power,74,71,68,70,T27,-1,283,2018
28,5cbe01638cc3ae72ca486ae5,"$52,360.00",28,Alex Cejka,70,71,71,71,T27,-1,283,2018
29,5cbe01638cc3ae72ca486ae6,"$52,360.00",28,Ted Potter Jr.,72,71,69,71,T27,-1,283,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
126,5cbe01668cc3ae72ca486b47,--,0,Whee Kim,76,73,--,--,-,CUT,149,2018
127,5cbe01668cc3ae72ca486b48,--,0,Kelly Kraft,76,73,--,--,-,CUT,149,2018
128,5cbe01668cc3ae72ca486b49,--,0,Denny McCarthy,76,73,--,--,-,CUT,149,2018
129,5cbe01668cc3ae72ca486b4a,--,0,Alexander Noren,73,76,--,--,-,CUT,149,2018
130,5cbe01668cc3ae72ca486b4b,--,0,Vijay Singh,74,75,--,--,-,CUT,149,2018
131,5cbe01668cc3ae72ca486b4c,--,0,Brian Stuard,78,71,--,--,-,CUT,149,2018
132,5cbe01668cc3ae72ca486b4d,--,0,Geoff Ogilvy,68,81,--,--,-,CUT,149,2018
133,5cbe01668cc3ae72ca486b4e,--,0,Kevin Streelman,79,71,--,--,-,CUT,150,2018
134,5cbe01668cc3ae72ca486b4f,--,0,Ryan Ruffels,78,72,--,--,-,CUT,150,2018
135,5cbe01668cc3ae72ca486b50,--,0,Abraham Ancer,72,78,--,--,-,CUT,150,2018
136,5cbe01668cc3ae72ca486b51,--,0,Nicholas Lindheim,75,75,--,--,-,CUT,150,2018
137,5cbe01668cc3ae72ca486b52,--,0,Anirban Lahiri,76,74,--,--,-,CUT,150,2018
138,5cbe01668cc3ae72ca486b53,--,0,Matt Every,79,72,--,--,-,CUT,151,2018
139,5cbe01668cc3ae72ca486b54,--,0,Rob Oppenheim,72,79,--,--,-,CUT,151,2018
140,5cbe01668cc3ae72ca486b55,--,0,Carter Jenkins,76,75,--,--,-,CUT,151,2018
141,5cbe01668cc3ae72ca486b56,--,0,Scott Stallings,79,73,--,--,-,CUT,152,2018
142,5cbe01668cc3ae72ca486b57,--,0,Kyle Thompson,74,78,--,--,-,CUT,152,2018
143,5cbe01668cc3ae72ca486b58,--,0,Adam Schenk,77,75,--,--,-,CUT,152,2018
144,5cbe01668cc3ae72ca486b59,--,0,Dru Love,79,74,--,--,-,CUT,153,2018
145,5cbe01668cc3ae72ca486b5a,--,0,Roberto Diaz,75,78,--,--,-,CUT,153,2018
146,5cbe01668cc3ae72ca486b5b,--,0,J.T. Griffin,79,74,--,--,-,CUT,153,2018
147,5cbe01668cc3ae72ca486b5c,--,0,Mito Pereira,81,73,--,--,-,CUT,154,2018
148,5cbe01668cc3ae72ca486b5d,--,0,Martin Piller,75,81,--,--,-,CUT,156,2018
149,5cbe01668cc3ae72ca486b5e,--,0,Charles Frost,82,77,--,--,-,CUT,159,2018
150,5cbe01668cc3ae72ca486b5f,--,0,Smylie Kaufman,80,79,--,--,-,CUT,159,2018
151,5cbe01668cc3ae72ca486b60,--,0,Derek Fathauer,83,80,--,--,-,CUT,163,2018
152,5cbe01668cc3ae72ca486b61,--,0,Bob Estes,77,--,--,--,-,WD,77,2018
153,5cbe01668cc3ae72ca486b62,--,0,Davis Love III,78,--,--,--,-,WD,78,2018
154,5cbe01668cc3ae72ca486b63,--,0,Andrew Landry,78,--,--,--,-,WD,78,2018
155,5cbe01668cc3ae72ca486b64,--,0,Steve Marino,80,39,--,--,-,WD,80,2018

In [81]:
raw_data_2018 = raw_data_2018[['name','year','r1','r2']].copy()
raw_data_2017 = raw_data_2017[raw_data_2017.score != 'CUT']
raw_data_2017 = raw_data_2017[raw_data_2017.score != 'E']
raw_data_2017 = raw_data_2017[raw_data_2017.score != 'WD']
raw_data_2017 = raw_data_2017[raw_data_2017.score != '--']
raw_data_2017['total']=raw_data_2017['total'].astype(float)
raw_data_2017['year']=raw_data_2017['year'].astype(float)
raw_data_2018['year']=raw_data_2018['year'].astype(float)
raw_data_2017['avg_round']= raw_data_2017['total']/4
raw_data_2017['year'] = raw_data_2017['year']+1

In [82]:
raw_data_2017

,_id,earnings,fedExPoints,name,r1,r2,r3,r4,rank,score,total,year,avg_round
156,5cbe01688cc3ae72ca486b65,"$1,350,000.00",500,Brian Harman,71,69,70,68,1,-10,278.0,2018.0,69.50
157,5cbe01688cc3ae72ca486b66,"$660,000.00",245,Dustin Johnson,70,75,67,67,T2,-9,279.0,2018.0,69.75
158,5cbe01688cc3ae72ca486b67,"$660,000.00",245,Pat Perez,72,69,70,68,T2,-9,279.0,2018.0,69.75
159,5cbe01688cc3ae72ca486b68,"$360,000.00",135,Jon Rahm,69,71,69,71,4,-8,280.0,2018.0,70.00
160,5cbe01688cc3ae72ca486b69,"$273,750.00",100,Smylie Kaufman,70,71,72,68,T5,-7,281.0,2018.0,70.25
161,5cbe01688cc3ae72ca486b6a,"$273,750.00",100,Kevin Tway,72,70,69,70,T5,-7,281.0,2018.0,70.25
162,5cbe01688cc3ae72ca486b6b,"$273,750.00",100,Seung-yul Noh,69,74,67,71,T5,-7,281.0,2018.0,70.25
163,5cbe01688cc3ae72ca486b6c,"$210,000.00",78,Jonathan Randolph,69,73,73,67,T8,-6,282.0,2018.0,70.50
164,5cbe01688cc3ae72ca486b6d,"$210,000.00",78,Billy Hurley III,70,69,72,71,T8,-6,282.0,2018.0,70.50
165,5cbe01688cc3ae72ca486b6e,"$210,000.00",78,Nick Taylor,71,69,71,71,T8,-6,282.0,2018.0,70.50
166,5cbe01688cc3ae72ca486b6f,"$210,000.00",78,Byeong-Hun An,72,70,69,71,T8,-6,282.0,2018.0,70.50
167,5cbe01688cc3ae72ca486b70,"$142,500.00",57,Paul Casey,70,75,70,68,T12,-5,283.0,2018.0,70.75
168,5cbe01688cc3ae72ca486b71,"$142,500.00",57,D.A. Points,73,69,73,68,T12,-5,283.0,2018.0,70.75
169,5cbe01698cc3ae72ca486b72,"$142,500.00",57,Morgan Hoffmann,70,71,71,71,T12,-5,283.0,2018.0,70.75
170,5cbe01698cc3ae72ca486b73,"$142,500.00",57,Zac Blair,72,70,69,72,T12,-5,283.0,2018.0,70.75
171,5cbe01698cc3ae72ca486b74,"$142,500.00",57,Vaughn Taylor,71,69,70,73,T12,-5,283.0,2018.0,70.75
172,5cbe01698cc3ae72ca486b75,"$142,500.00",57,Patrick Reed,70,71,67,75,T12,-5,283.0,2018.0,70.75
173,5cbe01698cc3ae72ca486b76,"$94,500.00",44,Brandon Hagy,73,71,71,69,T18,-4,284.0,2018.0,71.00
174,5cbe01698cc3ae72ca486b77,"$94,500.00",44,Ben Martin,68,72,74,70,T18,-4,284.0,2018.0,71.00
175,5cbe01698cc3ae72ca486b78,"$94,500.00",44,Zach Johnson,71,73,69,71,T18,-4,284.0,2018.0,71.00
176,5cbe01698cc3ae72ca486b79,"$94,500.00",44,David Lingmerth,72,70,70,72,T18,-4,284.0,2018.0,71.00
177,5cbe01698cc3ae72ca486b7a,"$94,500.00",44,Graeme McDowell,71,71,70,72,T18,-4,284.0,2018.0,71.00
178,5cbe01698cc3ae72ca486b7b,"$94,500.00",44,Phil Mickelson,71,72,69,72,T18,-4,284.0,2018.0,71.00
179,5cbe01698cc3ae72ca486b7c,"$59,357.15",33,Xander Schauffele,71,70,76,68,T24,-3,285.0,2018.0,71.25
180,5cbe01698cc3ae72ca486b7d,"$59,357.15",33,Robert Streb,72,71,72,70,T24,-3,285.0,2018.0,71.25
181,5cbe01698cc3ae72ca486b7e,"$59,357.14",33,J.T. Poston,71,73,70,71,T24,-3,285.0,2018.0,71.25
182,5cbe01698cc3ae72ca486b7f,"$59,357.14",33,Rafael Cabrera Bello,69,71,73,72,T24,-3,285.0,2018.0,71.25
183,5cbe01698cc3ae72ca486b80,"$59,357.14",33,Shane Lowry,75,70,68,72,T24,-3,285.0,2018.0,71.25
184,5cbe01698cc3ae72ca486b81,"$59,357.14",33,Mark D. Anderson,70,72,71,72,T24,-3,285.0,2018.0,71.25
185,5cbe01698cc3ae72ca486b82,"$59,357.14",33,Francesco Molinari,66,72,72,75,T24,-3,285.0,2018.0,71.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,5cbe01698cc3ae72ca486b96,"$18,950.00",9,Seamus Power,68,71,77,73,T49,+1,289.0,2018.0,72.25
206,5cbe01698cc3ae72ca486b97,"$18,950.00",9,Retief Goosen,70,72,73,74,T49,+1,289.0,2018.0,72.25
207,5cbe01698cc3ae72ca486b98,"$17,314.29",6,Lucas Glover,71,73,76,70,T52,+2,290.0,2018.0,72.50
208,5cbe01698cc3ae72ca486b99,"$17,314.29",0,Curtis Luck,72,73,73,72,T52,+2,290.0,2018.0,72.50
209,5cbe01698cc3ae72ca486b9a,"$17,314.29",6,Luke List,72,71,74,73,T52,+2,290.0,2018.0,72.50
210,5cbe01698cc3ae72ca486b9b,"$17,314.29",6,Hunter Mahan,72,73,71,74,T52,+2,290.0,2018.0,72.50
211,5cbe01698cc3ae72ca486b9c,"$17,314.28",0,Robby Shelton,73,72,70,75,T52,+2,290.0,2018.0,72.50
212,5cbe01698cc3ae72ca486b9d,"$17,314.28",6,Tyler Aldridge,74,70,71,75,T52,+2,290.0,2018.0,72.50
213,5cbe01698cc3ae72ca486b9e,"$17,314.28",6,Brian Gay,70,72,71,77,T52,+2,290.0,2018.0,72.50
214,5cbe01698cc3ae72ca486b9f,"$16,425.00",0,Justin Lower,71,73,75,72,T59,+3,291.0,2018.0,72.75
215,5cbe016a8cc3ae72ca486ba0,"$16,425.00",5,James Hahn,72,71,75,73,T59,+3,291.0,2018.0,72.75
216,5cbe016a8cc3ae72ca486ba1,"$16,425.00",5,Ryan Armour,71,72,75,73,T59,+3,291.0,2018.0,72.75
217,5cbe016a8cc3ae72ca486ba2,"$16,425.00",5,Nick Watney,71,74,70,76,T59,+3,291.0,2018.0,72.75
218,5cbe016a8cc3ae72ca486ba3,"$15,900.00",4,Shawn Stefani,69,72,77,74,T63,+4,292.0,2018.0,73.00
219,5cbe016a8cc3ae72ca486ba4,"$15,900.00",4,Grayson Murray,67,73,76,76,T63,+4,292.0,2018.0,73.00
220,5cbe016a8cc3ae72ca486ba5,"$15,900.00",4,Ricky Barnes,73,72,70,77,T63,+4,292.0,2018.0,73.00
221,5cbe016a8cc3ae72ca486ba6,"$15,300.00",3,J.J. Henry,71,74,75,73,T66,+5,293.0,2018.0,73.25
222,5cbe016a8cc3ae72ca486ba7,"$15,300.00",3,Jason Kokrak,71,74,75,73,T66,+5,293.0,2018.0,73.25
223,5cbe016a8cc3ae72ca486ba8,"$15,300.00",3,Ryan Blaum,72,73,74,74,T66,+5,293.0,2018.0,73.25
224,5cbe016a8cc3ae72ca486ba9,"$15,300.00",3,Matt Jones,72,72,74,75,T66,+5,293.0,2018.0,73.25
225,5cbe016a8cc3ae72ca486baa,"$15,300.00",3,Patton Kizzire,73,71,72,77,T66,+5,293.0,2018.0,73.25
226,5cbe016a8cc3ae72ca486bab,"$14,775.00",3,Chris Kirk,69,76,75,76,T71,+8,296.0,2018.0,74.00
227,5cbe016a8cc3ae72ca486bac,"$14,775.00",3,Brad Fritsch,73,71,74,78,T71,+8,296.0,2018.0,74.00
228,5cbe016a8cc3ae72ca486bad,"$14,550.00",3,Miguel Angel Carballo,75,70,74,78,73,+9,297.0,2018.0,74.25
229,5cbe016a8cc3ae72ca486bae,"$14,400.00",3,Ken Duke,68,76,76,78,74,+10,298.0,2018.0,74.50
230,5cbe016a8cc3ae72ca486baf,"$14,250.00",3,Fabian Gomez,71,73,77,--,75,+5,221.0,2018.0,55.25
231,5cbe016a8cc3ae72ca486bb0,"$13,875.00",2,Greg Owen,70,75,77,--,T76,+6,222.0,2018.0,55.50
232,5cbe016a8cc3ae72ca486bb1,"$13,875.00",2,Jason Bohn,75,70,77,--,T76,+6,222.0,2018.0,55.50
233,5cbe016a8cc3ae72ca486bb2,"$13,875.00",2,Martin Flores,74,71,77,--,T76,+6,222.0,2018.0,55.50
234,5cbe016a8cc3ae72ca486bb3,"$13,875.00",2,Steven Alker,74,71,77,--,T76,+6,222.0,2018.0,55.50

In [83]:
data_test1 = pd.merge(raw_data_2017,raw_data_2018, on=['name','year'], how='inner')
data_test2 = data_test1[['avg_round','r1_y','r2_y']]
data_test2 = data_test2.astype(float)
data_test2

    avg_round  r1_y  r2_y
0       69.50  72.0  73.0
1       70.25  80.0  79.0
2       70.25  73.0  73.0
3       70.50  74.0  69.0
4       70.50  71.0  74.0
5       70.50  77.0  70.0
6       70.50  73.0  70.0
7       70.75  69.0  68.0
8       70.75  76.0  71.0
9       70.75  74.0  68.0
10      70.75  71.0  71.0
11      71.00  73.0  74.0
12      71.00  71.0  73.0
13      71.00  72.0  72.0
14      71.25  74.0  71.0
15      71.25  73.0  72.0
16      71.25  78.0  69.0
17      71.25  74.0  70.0
18      71.25  70.0  72.0
19      71.50  71.0  73.0
20      71.50  73.0  76.0
21      71.75  75.0  70.0
22      71.75  73.0  69.0
23      71.75  71.0  73.0
24      71.75  65.0  77.0
25      72.25  70.0  76.0
26      72.25  74.0  71.0
27      72.25  77.0  69.0
28      72.50  74.0  74.0
29      72.50  70.0  72.0
30      72.75  74.0  73.0
31      72.75  72.0  67.0
32      73.00  71.0  69.0
33      73.00  73.0  71.0
34      73.25  73.0  72.0
35      73.25  74.0  72.0
36      73.25  75.0  70.0
37      73.25  75.0  73.0
38      55.25  71.0  74.0
39      55.50  72.0  73.0

In [84]:
data_test2['y2'] = np.where(data_test2['r2_y']<=data_test2['avg_round'],1,0) 
data_test2['r1_lt_avg'] = np.where(data_test2['r1_y']<=data_test2['avg_round'],1,0)

In [85]:
data_test = data_test2.copy()
data_test

    avg_round  r1_y  r2_y  y2  r1_lt_avg
0       69.50  72.0  73.0   0          0
1       70.25  80.0  79.0   0          0
2       70.25  73.0  73.0   0          0
3       70.50  74.0  69.0   1          0
4       70.50  71.0  74.0   0          0
5       70.50  77.0  70.0   1          0
6       70.50  73.0  70.0   1          0
7       70.75  69.0  68.0   1          1
8       70.75  76.0  71.0   0          0
9       70.75  74.0  68.0   1          0
10      70.75  71.0  71.0   0          0
11      71.00  73.0  74.0   0          0
12      71.00  71.0  73.0   0          1
13      71.00  72.0  72.0   0          0
14      71.25  74.0  71.0   1          0
15      71.25  73.0  72.0   0          0
16      71.25  78.0  69.0   1          0
17      71.25  74.0  70.0   1          0
18      71.25  70.0  72.0   0          1
19      71.50  71.0  73.0   0          1
20      71.50  73.0  76.0   0          0
21      71.75  75.0  70.0   1          0
22      71.75  73.0  69.0   1          0
23      71.75  71.0  73.0   0          1
24      71.75  65.0  77.0   0          1
25      72.25  70.0  76.0   0          1
26      72.25  74.0  71.0   1          0
27      72.25  77.0  69.0   1          0
28      72.50  74.0  74.0   0          0
29      72.50  70.0  72.0   1          1
30      72.75  74.0  73.0   0          0
31      72.75  72.0  67.0   1          1
32      73.00  71.0  69.0   1          1
33      73.00  73.0  71.0   1          1
34      73.25  73.0  72.0   1          1
35      73.25  74.0  72.0   1          0
36      73.25  75.0  70.0   1          0
37      73.25  75.0  73.0   1          0
38      55.25  71.0  74.0   0          0
39      55.50  72.0  73.0   0          0

In [86]:
y_test = data_test['y2']
x1_test = data_test[['r1_lt_avg','avg_round']]
x_test = sm.add_constant(x1_test)

In [87]:
confusion_matrix(x_test, y_test, results_log)

(array([[17.00, 3.00],
        [12.00, 8.00]]), 0.625)